precompile(Tuple{typeof(Base.display_error), Array{Any, 1}})
precompile(Tuple{typeof(Base.show_exception_stack), Base.IOContext{Base.TTY}, Array{Any, 1}})
precompile(Tuple{typeof(Base.display_error), Base.TTY, Array{Any, 1}})
precompile(Tuple{getfield(Base, Symbol("#kw##printstyled")), NamedTuple{(:bold, :color), Tuple{Bool, Symbol}}, typeof(Base.printstyled), Base.TTY, String})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{ErrorException, Array{Union{Ptr{Nothing}, Base.InterpreterIP}, 1}}, Int64})
precompile(Tuple{typeof(Base.indexed_iterate), Tuple{ErrorException, Array{Union{Ptr{Nothing}, Base.InterpreterIP}, 1}}, Int64, Int64})
precompile(Tuple{typeof(Base.show_reduced_backtrace), Base.IOContext{Base.TTY}, Array{Any, 1}, Bool})
precompile(Tuple{typeof(Base.show_backtrace), Base.IOContext{Base.TTY}, Array{Union{Ptr{Nothing}, Base.InterpreterIP}, 1}})
precompile(Tuple{getfield(Base, Symbol("##showerror#656")), Bool, typeof(Base.showerror), Base.IOContext{Base.TTY}, ErrorException, Array{Union{Ptr{Nothing}, Base.InterpreterIP}, 1}})
precompile(Tuple{getfield(Base, Symbol("#kw##showerror")), NamedTuple{(:backtrace,), Tuple{Bool}}, typeof(Base.showerror), Base.IOContext{Base.TTY}, ErrorException, Array{Union{Ptr{Nothing}, Base.InterpreterIP}, 1}})
precompile(Tuple{getfield(Base, Symbol("##with_output_color#707")), Bool, typeof(Base.with_output_color), Function, Symbol, Base.IOContext{Base.TTY}})
precompile(Tuple{typeof(Base.with_output_color), Function, Symbol, Base.IOContext{Base.TTY}})
precompile(Tuple{getfield(Base, Symbol("#657#658")){ErrorException}, Base.IOContext{Base.GenericIOBuffer{Array{UInt8, 1}}}})
precompile(Tuple{typeof(Base.print), Base.IOContext{Base.TTY}, String, String})
precompile(Tuple{typeof(Base.join), Base.IOContext{Base.TTY}, Array{String, 1}, String, String})
precompile(Tuple{typeof(Base.show_method_params), Base.IOContext{Base.TTY}, Array{Any, 1}})
precompile(Tuple{typeof(Base.show), Base.IOContext{Base.TTY}, Module})
precompile(Tuple{typeof(Base.print), Base.IOContext{Base.TTY}, Module})
precompile(Tuple{typeof(Base.print), Base.IOContext{Base.TTY}, String, Module})
precompile(Tuple{getfield(Base, Symbol("##show#393")), Nothing, typeof(Base.show), Base.IOContext{Base.TTY}, Method})
precompile(Tuple{typeof(Base.show), Base.IOContext{Base.TTY}, Core.MethodInstance})
precompile(Tuple{getfield(Base, Symbol("##show#379")), Symbol, typeof(Base.show), Base.IOContext{Base.TTY}, Core.CodeInfo})
precompile(Tuple{typeof(Base.StackTraces.show_spec_linfo), Base.IOContext{Base.TTY}, Base.StackTraces.StackFrame})
precompile(Tuple{getfield(Base.StackTraces, Symbol("##show#9")), Bool, typeof(Base.show), Base.IOContext{Base.TTY}, Base.StackTraces.StackFrame})
precompile(Tuple{getfield(Base, Symbol("##show_trace_entry#673")), String, typeof(Base.show_trace_entry), Base.IOContext{Base.TTY}, Base.StackTraces.StackFrame, Int64})
precompile(Tuple{getfield(Base, Symbol("#kw##show_trace_entry")), NamedTuple{(:prefix,), Tuple{String}}, typeof(Base.show_trace_entry), Base.IOContext{Base.TTY}, Base.StackTraces.StackFrame, Int64})
precompile(Tuple{Type{NamedTuple{(:color,), T} where T<:Tuple}, Tuple{Symbol}})
precompile(Tuple{getfield(Base, Symbol("#kw##printstyled")), NamedTuple{(:color,), Tuple{Symbol}}, typeof(Base.printstyled), Base.IOContext{Base.TTY}, String})
precompile(Tuple{getfield(Base, Symbol("##with_output_color#707")), Bool, typeof(Base.with_output_color), Function, Symbol, Base.IOContext{Base.TTY}, String})
precompile(Tuple{typeof(Base.show_tuple_as_call), Base.IOContext{Base.TTY}, Symbol, Type})
precompile(Tuple{typeof(Base.print), Base.IOContext{Base.TTY}, String, Type{T} where T})
precompile(Tuple{typeof(Base.print), Base.IOContext{Base.TTY}, Type})
precompile(Tuple{typeof(Base.show_sym), Base.IOContext{Base.TTY}, String})
precompile(Tuple{getfield(Base, Symbol("##show_sym#371")), Bool, typeof(Base.show_sym), Base.IOContext{Base.TTY}, String})
precompile(Tuple{getfield(Base, Symbol("##show_sym#371")), Bool, typeof(Base.show_sym), Base.IOContext{Base.TTY}, Symbol})
precompile(Tuple{typeof(Base.show_type_name), Base.IOContext{Base.TTY}, Core.TypeName})
precompile(Tuple{typeof(Base.show_datatype), Base.IOContext{Base.TTY}, DataType})
precompile(Tuple{typeof(Base.show_delim_array), Base.IOContext{Base.TTY}, Array{Any, 1}, Char, Char, Char, Bool, Int64, Int64})
precompile(Tuple{typeof(Base.show), Base.IOContext{Base.TTY}, Type})
